name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --command npm clean-install
      - run: nix develop --command npm run test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_name == 'main' }}
    env:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop --command npm clean-install
      - run: nix develop --command npm run release:candidate
