name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --command yarn install
      - run: nix develop --command yarn -s test
      - run: nix develop --command yarn pack
